// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/survey/fhir.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ondewo.Survey {

  /// <summary>Holder for reflection information generated from ondewo/survey/fhir.proto</summary>
  public static partial class FhirReflection {

    #region Descriptor
    /// <summary>File descriptor for ondewo/survey/fhir.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FhirReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhvbmRld28vc3VydmV5L2ZoaXIucHJvdG8SDW9uZGV3by5zdXJ2ZXkaHGdv",
            "b2dsZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aGm9uZGV3by9zdXJ2ZXkvc3Vy",
            "dmV5LnByb3RvGhxnb29nbGUvcHJvdG9idWYvc3RydWN0LnByb3RvIk4KF0Ny",
            "ZWF0ZUZISVJTdXJ2ZXlSZXF1ZXN0EjMKEmZoaXJfcXVlc3Rpb25uYWlyZRgB",
            "IAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QibQoZU3VydmV5RkhJUkFu",
            "c3dlcnNSZXNwb25zZRIRCglzdXJ2ZXlfaWQYASABKAkSPQocZmhpcl9xdWVz",
            "dGlvbm5haXJlX3Jlc3BvbnNlcxgCIAMoCzIXLmdvb2dsZS5wcm90b2J1Zi5T",
            "dHJ1Y3QytQMKBEZISVISagoQQ3JlYXRlRkhJUlN1cnZleRImLm9uZGV3by5z",
            "dXJ2ZXkuQ3JlYXRlRkhJUlN1cnZleVJlcXVlc3QaFS5vbmRld28uc3VydmV5",
            "LlN1cnZleSIXgtPkkwIRIgwvZmhpcl9zdXJ2ZXk6ASoSowEKFEdldEZISVJT",
            "dXJ2ZXlBbnN3ZXJzEiYub25kZXdvLnN1cnZleS5HZXRTdXJ2ZXlBbnN3ZXJz",
            "UmVxdWVzdBooLm9uZGV3by5zdXJ2ZXkuU3VydmV5RkhJUkFuc3dlcnNSZXNw",
            "b25zZSI5gtPkkwIzEjEvc3VydmV5L3tzdXJ2ZXlfaWQ9Kn0vZmhpcl9hbnN3",
            "ZXJzL3tzZXNzaW9uX2lkPSp9EpoBChdHZXRBbGxGSElSU3VydmV5QW5zd2Vy",
            "cxIpLm9uZGV3by5zdXJ2ZXkuR2V0QWxsU3VydmV5QW5zd2Vyc1JlcXVlc3Qa",
            "KC5vbmRld28uc3VydmV5LlN1cnZleUZISVJBbnN3ZXJzUmVzcG9uc2UiKoLT",
            "5JMCJBIiL3N1cnZleS97c3VydmV5X2lkPSp9L2ZoaXJfYW5zd2Vyc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Ondewo.Survey.SurveyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ondewo.Survey.CreateFHIRSurveyRequest), global::Ondewo.Survey.CreateFHIRSurveyRequest.Parser, new[]{ "FhirQuestionnaire" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ondewo.Survey.SurveyFHIRAnswersResponse), global::Ondewo.Survey.SurveyFHIRAnswersResponse.Parser, new[]{ "SurveyId", "FhirQuestionnaireResponses" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreateFHIRSurveyRequest : pb::IMessage<CreateFHIRSurveyRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateFHIRSurveyRequest> _parser = new pb::MessageParser<CreateFHIRSurveyRequest>(() => new CreateFHIRSurveyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateFHIRSurveyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ondewo.Survey.FhirReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateFHIRSurveyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateFHIRSurveyRequest(CreateFHIRSurveyRequest other) : this() {
      fhirQuestionnaire_ = other.fhirQuestionnaire_ != null ? other.fhirQuestionnaire_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateFHIRSurveyRequest Clone() {
      return new CreateFHIRSurveyRequest(this);
    }

    /// <summary>Field number for the "fhir_questionnaire" field.</summary>
    public const int FhirQuestionnaireFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Struct fhirQuestionnaire_;
    /// <summary>
    /// FHIR questionnaire on a gRPC Struct format
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct FhirQuestionnaire {
      get { return fhirQuestionnaire_; }
      set {
        fhirQuestionnaire_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateFHIRSurveyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateFHIRSurveyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FhirQuestionnaire, other.FhirQuestionnaire)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (fhirQuestionnaire_ != null) hash ^= FhirQuestionnaire.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (fhirQuestionnaire_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FhirQuestionnaire);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (fhirQuestionnaire_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FhirQuestionnaire);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (fhirQuestionnaire_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FhirQuestionnaire);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateFHIRSurveyRequest other) {
      if (other == null) {
        return;
      }
      if (other.fhirQuestionnaire_ != null) {
        if (fhirQuestionnaire_ == null) {
          FhirQuestionnaire = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        FhirQuestionnaire.MergeFrom(other.FhirQuestionnaire);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (fhirQuestionnaire_ == null) {
              FhirQuestionnaire = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(FhirQuestionnaire);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (fhirQuestionnaire_ == null) {
              FhirQuestionnaire = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(FhirQuestionnaire);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SurveyFHIRAnswersResponse : pb::IMessage<SurveyFHIRAnswersResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SurveyFHIRAnswersResponse> _parser = new pb::MessageParser<SurveyFHIRAnswersResponse>(() => new SurveyFHIRAnswersResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SurveyFHIRAnswersResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ondewo.Survey.FhirReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SurveyFHIRAnswersResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SurveyFHIRAnswersResponse(SurveyFHIRAnswersResponse other) : this() {
      surveyId_ = other.surveyId_;
      fhirQuestionnaireResponses_ = other.fhirQuestionnaireResponses_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SurveyFHIRAnswersResponse Clone() {
      return new SurveyFHIRAnswersResponse(this);
    }

    /// <summary>Field number for the "survey_id" field.</summary>
    public const int SurveyIdFieldNumber = 1;
    private string surveyId_ = "";
    /// <summary>
    /// The project identifier for this survey. Equal to the parent of the corresponding Agent.
    /// Format: `projects/&lt;Project ID>/agent`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SurveyId {
      get { return surveyId_; }
      set {
        surveyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fhir_questionnaire_responses" field.</summary>
    public const int FhirQuestionnaireResponsesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Struct> _repeated_fhirQuestionnaireResponses_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Protobuf.WellKnownTypes.Struct.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Struct> fhirQuestionnaireResponses_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Struct>();
    /// <summary>
    /// all requested answers
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Struct> FhirQuestionnaireResponses {
      get { return fhirQuestionnaireResponses_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SurveyFHIRAnswersResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SurveyFHIRAnswersResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SurveyId != other.SurveyId) return false;
      if(!fhirQuestionnaireResponses_.Equals(other.fhirQuestionnaireResponses_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SurveyId.Length != 0) hash ^= SurveyId.GetHashCode();
      hash ^= fhirQuestionnaireResponses_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SurveyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SurveyId);
      }
      fhirQuestionnaireResponses_.WriteTo(output, _repeated_fhirQuestionnaireResponses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SurveyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SurveyId);
      }
      fhirQuestionnaireResponses_.WriteTo(ref output, _repeated_fhirQuestionnaireResponses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SurveyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SurveyId);
      }
      size += fhirQuestionnaireResponses_.CalculateSize(_repeated_fhirQuestionnaireResponses_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SurveyFHIRAnswersResponse other) {
      if (other == null) {
        return;
      }
      if (other.SurveyId.Length != 0) {
        SurveyId = other.SurveyId;
      }
      fhirQuestionnaireResponses_.Add(other.fhirQuestionnaireResponses_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SurveyId = input.ReadString();
            break;
          }
          case 18: {
            fhirQuestionnaireResponses_.AddEntriesFrom(input, _repeated_fhirQuestionnaireResponses_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SurveyId = input.ReadString();
            break;
          }
          case 18: {
            fhirQuestionnaireResponses_.AddEntriesFrom(ref input, _repeated_fhirQuestionnaireResponses_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
