// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/survey/fhir.proto
// </auto-generated>
// Original file comments:
// Copyright 2020 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. (editesyntax = "proto3";
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Survey {
  public static partial class FHIR
  {
    static readonly string __ServiceName = "ondewo.survey.FHIR";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.CreateFHIRSurveyRequest> __Marshaller_ondewo_survey_CreateFHIRSurveyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.CreateFHIRSurveyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.Survey> __Marshaller_ondewo_survey_Survey = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.Survey.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.GetSurveyAnswersRequest> __Marshaller_ondewo_survey_GetSurveyAnswersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.GetSurveyAnswersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.SurveyFHIRAnswersResponse> __Marshaller_ondewo_survey_SurveyFHIRAnswersResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.SurveyFHIRAnswersResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.GetAllSurveyAnswersRequest> __Marshaller_ondewo_survey_GetAllSurveyAnswersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.GetAllSurveyAnswersRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.CreateFHIRSurveyRequest, global::Ondewo.Survey.Survey> __Method_CreateFHIRSurvey = new grpc::Method<global::Ondewo.Survey.CreateFHIRSurveyRequest, global::Ondewo.Survey.Survey>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateFHIRSurvey",
        __Marshaller_ondewo_survey_CreateFHIRSurveyRequest,
        __Marshaller_ondewo_survey_Survey);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.GetSurveyAnswersRequest, global::Ondewo.Survey.SurveyFHIRAnswersResponse> __Method_GetFHIRSurveyAnswers = new grpc::Method<global::Ondewo.Survey.GetSurveyAnswersRequest, global::Ondewo.Survey.SurveyFHIRAnswersResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFHIRSurveyAnswers",
        __Marshaller_ondewo_survey_GetSurveyAnswersRequest,
        __Marshaller_ondewo_survey_SurveyFHIRAnswersResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.GetAllSurveyAnswersRequest, global::Ondewo.Survey.SurveyFHIRAnswersResponse> __Method_GetAllFHIRSurveyAnswers = new grpc::Method<global::Ondewo.Survey.GetAllSurveyAnswersRequest, global::Ondewo.Survey.SurveyFHIRAnswersResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllFHIRSurveyAnswers",
        __Marshaller_ondewo_survey_GetAllSurveyAnswersRequest,
        __Marshaller_ondewo_survey_SurveyFHIRAnswersResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Survey.FhirReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FHIR</summary>
    [grpc::BindServiceMethod(typeof(FHIR), "BindService")]
    public abstract partial class FHIRBase
    {
      /// <summary>
      /// Create a Survey from FHIR format and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.Survey> CreateFHIRSurvey(global::Ondewo.Survey.CreateFHIRSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Get Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.SurveyFHIRAnswersResponse> GetFHIRSurveyAnswers(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Get all Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.SurveyFHIRAnswersResponse> GetAllFHIRSurveyAnswers(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FHIR</summary>
    public partial class FHIRClient : grpc::ClientBase<FHIRClient>
    {
      /// <summary>Creates a new client for FHIR</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public FHIRClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FHIR that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public FHIRClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected FHIRClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected FHIRClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Create a Survey from FHIR format and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey CreateFHIRSurvey(global::Ondewo.Survey.CreateFHIRSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateFHIRSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a Survey from FHIR format and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey CreateFHIRSurvey(global::Ondewo.Survey.CreateFHIRSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateFHIRSurvey, null, options, request);
      }
      /// <summary>
      /// Create a Survey from FHIR format and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> CreateFHIRSurveyAsync(global::Ondewo.Survey.CreateFHIRSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateFHIRSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a Survey from FHIR format and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> CreateFHIRSurveyAsync(global::Ondewo.Survey.CreateFHIRSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateFHIRSurvey, null, options, request);
      }
      /// <summary>
      /// Get Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyFHIRAnswersResponse GetFHIRSurveyAnswers(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFHIRSurveyAnswers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyFHIRAnswersResponse GetFHIRSurveyAnswers(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFHIRSurveyAnswers, null, options, request);
      }
      /// <summary>
      /// Get Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyFHIRAnswersResponse> GetFHIRSurveyAnswersAsync(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFHIRSurveyAnswersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyFHIRAnswersResponse> GetFHIRSurveyAnswersAsync(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFHIRSurveyAnswers, null, options, request);
      }
      /// <summary>
      /// Get all Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyFHIRAnswersResponse GetAllFHIRSurveyAnswers(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllFHIRSurveyAnswers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get all Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyFHIRAnswersResponse GetAllFHIRSurveyAnswers(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllFHIRSurveyAnswers, null, options, request);
      }
      /// <summary>
      /// Get all Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyFHIRAnswersResponse> GetAllFHIRSurveyAnswersAsync(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllFHIRSurveyAnswersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Get all Survey Answers on FHIR format
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyFHIRAnswersResponse> GetAllFHIRSurveyAnswersAsync(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllFHIRSurveyAnswers, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override FHIRClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FHIRClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(FHIRBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateFHIRSurvey, serviceImpl.CreateFHIRSurvey)
          .AddMethod(__Method_GetFHIRSurveyAnswers, serviceImpl.GetFHIRSurveyAnswers)
          .AddMethod(__Method_GetAllFHIRSurveyAnswers, serviceImpl.GetAllFHIRSurveyAnswers).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FHIRBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateFHIRSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.CreateFHIRSurveyRequest, global::Ondewo.Survey.Survey>(serviceImpl.CreateFHIRSurvey));
      serviceBinder.AddMethod(__Method_GetFHIRSurveyAnswers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.GetSurveyAnswersRequest, global::Ondewo.Survey.SurveyFHIRAnswersResponse>(serviceImpl.GetFHIRSurveyAnswers));
      serviceBinder.AddMethod(__Method_GetAllFHIRSurveyAnswers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.GetAllSurveyAnswersRequest, global::Ondewo.Survey.SurveyFHIRAnswersResponse>(serviceImpl.GetAllFHIRSurveyAnswers));
    }

  }
}
#endregion
