// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/survey/survey.proto
// </auto-generated>
// Original file comments:
// Copyright 2020 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. (editesyntax = "proto3";
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Survey {
  public static partial class Surveys
  {
    static readonly string __ServiceName = "ondewo.survey.Surveys";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.CreateSurveyRequest> __Marshaller_ondewo_survey_CreateSurveyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.CreateSurveyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.Survey> __Marshaller_ondewo_survey_Survey = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.Survey.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.GetSurveyRequest> __Marshaller_ondewo_survey_GetSurveyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.GetSurveyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.UpdateSurveyRequest> __Marshaller_ondewo_survey_UpdateSurveyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.UpdateSurveyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.DeleteSurveyRequest> __Marshaller_ondewo_survey_DeleteSurveyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.DeleteSurveyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.ListSurveysRequest> __Marshaller_ondewo_survey_ListSurveysRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.ListSurveysRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.ListSurveysResponse> __Marshaller_ondewo_survey_ListSurveysResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.ListSurveysResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.GetSurveyAnswersRequest> __Marshaller_ondewo_survey_GetSurveyAnswersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.GetSurveyAnswersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.SurveyAnswersResponse> __Marshaller_ondewo_survey_SurveyAnswersResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.SurveyAnswersResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.GetAllSurveyAnswersRequest> __Marshaller_ondewo_survey_GetAllSurveyAnswersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.GetAllSurveyAnswersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.AgentSurveyRequest> __Marshaller_ondewo_survey_AgentSurveyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.AgentSurveyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Survey.AgentSurveyResponse> __Marshaller_ondewo_survey_AgentSurveyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Survey.AgentSurveyResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.CreateSurveyRequest, global::Ondewo.Survey.Survey> __Method_CreateSurvey = new grpc::Method<global::Ondewo.Survey.CreateSurveyRequest, global::Ondewo.Survey.Survey>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateSurvey",
        __Marshaller_ondewo_survey_CreateSurveyRequest,
        __Marshaller_ondewo_survey_Survey);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.GetSurveyRequest, global::Ondewo.Survey.Survey> __Method_GetSurvey = new grpc::Method<global::Ondewo.Survey.GetSurveyRequest, global::Ondewo.Survey.Survey>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSurvey",
        __Marshaller_ondewo_survey_GetSurveyRequest,
        __Marshaller_ondewo_survey_Survey);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.UpdateSurveyRequest, global::Ondewo.Survey.Survey> __Method_UpdateSurvey = new grpc::Method<global::Ondewo.Survey.UpdateSurveyRequest, global::Ondewo.Survey.Survey>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateSurvey",
        __Marshaller_ondewo_survey_UpdateSurveyRequest,
        __Marshaller_ondewo_survey_Survey);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.DeleteSurveyRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteSurvey = new grpc::Method<global::Ondewo.Survey.DeleteSurveyRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteSurvey",
        __Marshaller_ondewo_survey_DeleteSurveyRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.ListSurveysRequest, global::Ondewo.Survey.ListSurveysResponse> __Method_ListSurveys = new grpc::Method<global::Ondewo.Survey.ListSurveysRequest, global::Ondewo.Survey.ListSurveysResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListSurveys",
        __Marshaller_ondewo_survey_ListSurveysRequest,
        __Marshaller_ondewo_survey_ListSurveysResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.GetSurveyAnswersRequest, global::Ondewo.Survey.SurveyAnswersResponse> __Method_GetSurveyAnswers = new grpc::Method<global::Ondewo.Survey.GetSurveyAnswersRequest, global::Ondewo.Survey.SurveyAnswersResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSurveyAnswers",
        __Marshaller_ondewo_survey_GetSurveyAnswersRequest,
        __Marshaller_ondewo_survey_SurveyAnswersResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.GetAllSurveyAnswersRequest, global::Ondewo.Survey.SurveyAnswersResponse> __Method_GetAllSurveyAnswers = new grpc::Method<global::Ondewo.Survey.GetAllSurveyAnswersRequest, global::Ondewo.Survey.SurveyAnswersResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllSurveyAnswers",
        __Marshaller_ondewo_survey_GetAllSurveyAnswersRequest,
        __Marshaller_ondewo_survey_SurveyAnswersResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.AgentSurveyRequest, global::Ondewo.Survey.AgentSurveyResponse> __Method_CreateAgentSurvey = new grpc::Method<global::Ondewo.Survey.AgentSurveyRequest, global::Ondewo.Survey.AgentSurveyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateAgentSurvey",
        __Marshaller_ondewo_survey_AgentSurveyRequest,
        __Marshaller_ondewo_survey_AgentSurveyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.AgentSurveyRequest, global::Ondewo.Survey.AgentSurveyResponse> __Method_UpdateAgentSurvey = new grpc::Method<global::Ondewo.Survey.AgentSurveyRequest, global::Ondewo.Survey.AgentSurveyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateAgentSurvey",
        __Marshaller_ondewo_survey_AgentSurveyRequest,
        __Marshaller_ondewo_survey_AgentSurveyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Survey.AgentSurveyRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteAgentSurvey = new grpc::Method<global::Ondewo.Survey.AgentSurveyRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteAgentSurvey",
        __Marshaller_ondewo_survey_AgentSurveyRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Survey.SurveyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Surveys</summary>
    [grpc::BindServiceMethod(typeof(Surveys), "BindService")]
    public abstract partial class SurveysBase
    {
      /// <summary>
      /// Create a Survey and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.Survey> CreateSurvey(global::Ondewo.Survey.CreateSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Retrieve a Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.Survey> GetSurvey(global::Ondewo.Survey.GetSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Update an existing Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.Survey> UpdateSurvey(global::Ondewo.Survey.UpdateSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Delete a survey and its associated agent (if existent)
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteSurvey(global::Ondewo.Survey.DeleteSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Returns the list of all surveys in the server
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.ListSurveysResponse> ListSurveys(global::Ondewo.Survey.ListSurveysRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Retrieve answers to survey questions collected in interactions with a survey agent for a specific session
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.SurveyAnswersResponse> GetSurveyAnswers(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Retrieve all answers to survey questions collected in interactions with a survey agent in any session
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.SurveyAnswersResponse> GetAllSurveyAnswers(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Populate and configures an NLU Agent from a Survey
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.AgentSurveyResponse> CreateAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Update an NLU agent from a survey
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Survey.AgentSurveyResponse> UpdateAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Deletes all data of an NLU agent associated to a survey
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Surveys</summary>
    public partial class SurveysClient : grpc::ClientBase<SurveysClient>
    {
      /// <summary>Creates a new client for Surveys</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SurveysClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Surveys that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SurveysClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SurveysClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SurveysClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Create a Survey and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey CreateSurvey(global::Ondewo.Survey.CreateSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a Survey and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey CreateSurvey(global::Ondewo.Survey.CreateSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateSurvey, null, options, request);
      }
      /// <summary>
      /// Create a Survey and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> CreateSurveyAsync(global::Ondewo.Survey.CreateSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Create a Survey and an empty NLU Agent for it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> CreateSurveyAsync(global::Ondewo.Survey.CreateSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateSurvey, null, options, request);
      }
      /// <summary>
      /// Retrieve a Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey GetSurvey(global::Ondewo.Survey.GetSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve a Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey GetSurvey(global::Ondewo.Survey.GetSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSurvey, null, options, request);
      }
      /// <summary>
      /// Retrieve a Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> GetSurveyAsync(global::Ondewo.Survey.GetSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve a Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> GetSurveyAsync(global::Ondewo.Survey.GetSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSurvey, null, options, request);
      }
      /// <summary>
      /// Update an existing Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey UpdateSurvey(global::Ondewo.Survey.UpdateSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update an existing Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.Survey UpdateSurvey(global::Ondewo.Survey.UpdateSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateSurvey, null, options, request);
      }
      /// <summary>
      /// Update an existing Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> UpdateSurveyAsync(global::Ondewo.Survey.UpdateSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update an existing Survey message from the Database and return it
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.Survey> UpdateSurveyAsync(global::Ondewo.Survey.UpdateSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateSurvey, null, options, request);
      }
      /// <summary>
      /// Delete a survey and its associated agent (if existent)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteSurvey(global::Ondewo.Survey.DeleteSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a survey and its associated agent (if existent)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteSurvey(global::Ondewo.Survey.DeleteSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteSurvey, null, options, request);
      }
      /// <summary>
      /// Delete a survey and its associated agent (if existent)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteSurveyAsync(global::Ondewo.Survey.DeleteSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a survey and its associated agent (if existent)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteSurveyAsync(global::Ondewo.Survey.DeleteSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteSurvey, null, options, request);
      }
      /// <summary>
      /// Returns the list of all surveys in the server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.ListSurveysResponse ListSurveys(global::Ondewo.Survey.ListSurveysRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListSurveys(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the list of all surveys in the server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.ListSurveysResponse ListSurveys(global::Ondewo.Survey.ListSurveysRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListSurveys, null, options, request);
      }
      /// <summary>
      /// Returns the list of all surveys in the server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.ListSurveysResponse> ListSurveysAsync(global::Ondewo.Survey.ListSurveysRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListSurveysAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the list of all surveys in the server
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.ListSurveysResponse> ListSurveysAsync(global::Ondewo.Survey.ListSurveysRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListSurveys, null, options, request);
      }
      /// <summary>
      /// Retrieve answers to survey questions collected in interactions with a survey agent for a specific session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyAnswersResponse GetSurveyAnswers(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSurveyAnswers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve answers to survey questions collected in interactions with a survey agent for a specific session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyAnswersResponse GetSurveyAnswers(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSurveyAnswers, null, options, request);
      }
      /// <summary>
      /// Retrieve answers to survey questions collected in interactions with a survey agent for a specific session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyAnswersResponse> GetSurveyAnswersAsync(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSurveyAnswersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve answers to survey questions collected in interactions with a survey agent for a specific session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyAnswersResponse> GetSurveyAnswersAsync(global::Ondewo.Survey.GetSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSurveyAnswers, null, options, request);
      }
      /// <summary>
      /// Retrieve all answers to survey questions collected in interactions with a survey agent in any session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyAnswersResponse GetAllSurveyAnswers(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllSurveyAnswers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve all answers to survey questions collected in interactions with a survey agent in any session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.SurveyAnswersResponse GetAllSurveyAnswers(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllSurveyAnswers, null, options, request);
      }
      /// <summary>
      /// Retrieve all answers to survey questions collected in interactions with a survey agent in any session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyAnswersResponse> GetAllSurveyAnswersAsync(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllSurveyAnswersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve all answers to survey questions collected in interactions with a survey agent in any session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.SurveyAnswersResponse> GetAllSurveyAnswersAsync(global::Ondewo.Survey.GetAllSurveyAnswersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllSurveyAnswers, null, options, request);
      }
      /// <summary>
      /// Populate and configures an NLU Agent from a Survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.AgentSurveyResponse CreateAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAgentSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Populate and configures an NLU Agent from a Survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.AgentSurveyResponse CreateAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateAgentSurvey, null, options, request);
      }
      /// <summary>
      /// Populate and configures an NLU Agent from a Survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.AgentSurveyResponse> CreateAgentSurveyAsync(global::Ondewo.Survey.AgentSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAgentSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Populate and configures an NLU Agent from a Survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.AgentSurveyResponse> CreateAgentSurveyAsync(global::Ondewo.Survey.AgentSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateAgentSurvey, null, options, request);
      }
      /// <summary>
      /// Update an NLU agent from a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.AgentSurveyResponse UpdateAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAgentSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update an NLU agent from a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Survey.AgentSurveyResponse UpdateAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateAgentSurvey, null, options, request);
      }
      /// <summary>
      /// Update an NLU agent from a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.AgentSurveyResponse> UpdateAgentSurveyAsync(global::Ondewo.Survey.AgentSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAgentSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update an NLU agent from a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Survey.AgentSurveyResponse> UpdateAgentSurveyAsync(global::Ondewo.Survey.AgentSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateAgentSurvey, null, options, request);
      }
      /// <summary>
      /// Deletes all data of an NLU agent associated to a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAgentSurvey(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes all data of an NLU agent associated to a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteAgentSurvey(global::Ondewo.Survey.AgentSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteAgentSurvey, null, options, request);
      }
      /// <summary>
      /// Deletes all data of an NLU agent associated to a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteAgentSurveyAsync(global::Ondewo.Survey.AgentSurveyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAgentSurveyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes all data of an NLU agent associated to a survey
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteAgentSurveyAsync(global::Ondewo.Survey.AgentSurveyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteAgentSurvey, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SurveysClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SurveysClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SurveysBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateSurvey, serviceImpl.CreateSurvey)
          .AddMethod(__Method_GetSurvey, serviceImpl.GetSurvey)
          .AddMethod(__Method_UpdateSurvey, serviceImpl.UpdateSurvey)
          .AddMethod(__Method_DeleteSurvey, serviceImpl.DeleteSurvey)
          .AddMethod(__Method_ListSurveys, serviceImpl.ListSurveys)
          .AddMethod(__Method_GetSurveyAnswers, serviceImpl.GetSurveyAnswers)
          .AddMethod(__Method_GetAllSurveyAnswers, serviceImpl.GetAllSurveyAnswers)
          .AddMethod(__Method_CreateAgentSurvey, serviceImpl.CreateAgentSurvey)
          .AddMethod(__Method_UpdateAgentSurvey, serviceImpl.UpdateAgentSurvey)
          .AddMethod(__Method_DeleteAgentSurvey, serviceImpl.DeleteAgentSurvey).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SurveysBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.CreateSurveyRequest, global::Ondewo.Survey.Survey>(serviceImpl.CreateSurvey));
      serviceBinder.AddMethod(__Method_GetSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.GetSurveyRequest, global::Ondewo.Survey.Survey>(serviceImpl.GetSurvey));
      serviceBinder.AddMethod(__Method_UpdateSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.UpdateSurveyRequest, global::Ondewo.Survey.Survey>(serviceImpl.UpdateSurvey));
      serviceBinder.AddMethod(__Method_DeleteSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.DeleteSurveyRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteSurvey));
      serviceBinder.AddMethod(__Method_ListSurveys, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.ListSurveysRequest, global::Ondewo.Survey.ListSurveysResponse>(serviceImpl.ListSurveys));
      serviceBinder.AddMethod(__Method_GetSurveyAnswers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.GetSurveyAnswersRequest, global::Ondewo.Survey.SurveyAnswersResponse>(serviceImpl.GetSurveyAnswers));
      serviceBinder.AddMethod(__Method_GetAllSurveyAnswers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.GetAllSurveyAnswersRequest, global::Ondewo.Survey.SurveyAnswersResponse>(serviceImpl.GetAllSurveyAnswers));
      serviceBinder.AddMethod(__Method_CreateAgentSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.AgentSurveyRequest, global::Ondewo.Survey.AgentSurveyResponse>(serviceImpl.CreateAgentSurvey));
      serviceBinder.AddMethod(__Method_UpdateAgentSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.AgentSurveyRequest, global::Ondewo.Survey.AgentSurveyResponse>(serviceImpl.UpdateAgentSurvey));
      serviceBinder.AddMethod(__Method_DeleteAgentSurvey, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Survey.AgentSurveyRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteAgentSurvey));
    }

  }
}
#endregion
